### ISSUE TITLE
[Bug] Cannot scroll using scroll-wheel while hovering over UI elements

### ISSUE THREAD

**Issue by ladifas** [ItsDnD/LootGoblin#1]
#### Issue or Error Description

Scrolling main page with mouse-wheel works when pointer is over the following areas:
- Grey space around UI elements
- Green title areas of UI elements
- Light grey areas forming the boxes of the 'Encounter - ' UI elements
- Light grey areas underneath the thin green lines of 'loot container' and 'magic item' UI elements
- Green buttons

Scrolling main page with mouse-wheel does not work when pointer is over the following areas:
- Menu areas for 'magic items' or 'loot containers'
- Menu areas for 'Encounter -' UI elements

This behaviour is presumably because those areas can themselves scroll when the lists exceed the area. However, it would be better if it were possible to scroll the main page when the lists do not exceed the area.

If this would be better as a feature report, I am happy to move it there.

#### Note

Apologies for not following the given template; I could not see how to fit this bug into it.

**Comment by ItsDnD** [comment]
Thank you for the feedback, ladifas. This is one of the things that I have been looking into over the past few weeks. I want to users to be able to scroll throughout the page unless they click into (focus?) on one of the UI elements such as the data grids. And do not worry about the template as I am not a stickler for it, this contains enough information, and it technically is a bug/feature, depending on how you look at it.

I think I may have found a solution, but I have not had the time to test it. I plan to do so as soon as possible.

**Comment by ItsDnD** [comment]
I've had the chance to test some changes to how the mouse wheel events are handled, but I do not know if it will be the proper way of doing so. If I make it to where the UI elements do not catch the mouse wheel events, it will prevent it all the time, requiring you to manually drag the scroll bar in the grids or using the up/down buttons. 

I will continue to test a few different solutions.

**Comment by ItsDnD** [comment]
@ladifas, I have released a patch in reference to c3727d9c60cab7d23511f099fc81df6c88fdc0ff that is meant to help with this issue. I will continue to look for a better solution as we progress. Let me know how this works for you.

Download the update here: [LootGoblin_v1.0.1](https://github.com/ItsDnD/LootGoblin/releases/tag/1.0.1)

**Comment by ladifas** [comment]
@ItsDnD Scrolling still doesn't work in any of the areas listed above, even when there is nothing in the lists. :(

**Comment by ladifas** [comment]
@ItsDnD The options in the menu do indeed correct the scrolling behaviour, although I didn't initially notice that the functionality was buries in the options menu. I'll keep all those options ticked for now, as my lists never exceed the boxes, but a more intuitive functionality, which detects whether or not the lists are overflowing, would obviously be better.

**Comment by ItsDnD** [comment]
Thank you for the feedback. I will continue to works towards a better solution for the mouse wheel scrolling.

As for the options, I pushed some updates that moved the options button to the header of the main page. I also moved that header to the windows opened when editing loot containers and magic items.

Download the update here: [LootGoblin_v1.0.2](https://github.com/ItsDnD/LootGoblin/releases/tag/1.0.2)
